[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://evtaxi.app"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51QJLuqA3rr6byWPzKE7b8GUDIz9ExFoqD1d8VcIY25fP0MnzuBrD4K0p960YPR6XQpK7aZeVXUsRh4zA5lsKY5Nx00m5Wgwu3c"
  STRIPE_SECRET_KEY = "sk_test_51QJLuqA3rr6byWPzVuWXbOV6VFBobHM0h6fp6zF0UFe6lPDlUjDr7OfNkaF1HGDjKRtLVQrifOnk4Ij5QrxWt8Ly00R66EOJoT"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"